// CommonJS, every file = module(default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-way')
require('./7-mind-grenade')
sayHi('Sally')
sayHi(names.sam)
sayHi(names.sean)